name: CD Pipeline
# Only trigger, when the build workflow succeeded
on:
    workflow_run:
      workflows: ["CI Pipeline"]
      types:
        - completed
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Pull Docker image 
      run: sudo docker pull ucapistran/calendar:latest
    - name: Delete old Docker container 
      run: docker rm -f calendar-container || true
    - name: Run Docker calendar container    
      env: 
        DB_CNN: ${{secrets.DB_CNN}}
        JWT_SECRET_SEED: ${{secrets.JWT_SECRET_SEED}}
      run: sudo docker run --env DB_CNN=$DB_CNN  --env JWT_SECRET_SEED=$JWT_SECRET_SEED --env PORT=8080 -d -p 8080:8080 --name calendar-container ucapistran/calendar
